### ISSUE TITLE
Double ReferenceDescription on browse hierarchy

### ISSUE THREAD

**Issue by comtel2000** [digitalpetri/opc-ua-stack#20]
With the browse method:
```
	UInteger nodeClassMask = UInteger.valueOf(NodeClass.Object.getValue() | NodeClass.Variable.getValue());
	UInteger resultMask = UInteger.valueOf(BrowseResultMask.All.getValue());
	BrowseDescription bd = new BrowseDescription(node, BrowseDirection.Forward, null, false, nodeClassMask, resultMask);
```
i got double entries for some Nodes.

Tested with server:
opc.tcp://opcua.demo-this.com:51210/UA/SampleServer

Nodes:
Objects/Server/Data
or
Objects/Server/Boilers

![image](https://cloud.githubusercontent.com/assets/2266347/13962911/671c91be-f063-11e5-9a76-37715d1bdac5.png)

**Comment by kevinherron** [comment]
Hi, can you please report this on [the UA client SDK issues page](https://github.com/digitalpetri/ua-client-sdk/issues).
