### ISSUE TITLE
DefaultCertificateManager ignores iteration index

### ISSUE THREAD

**Issue by lightningrob** [digitalpetri/opc-ua-stack#24]
This can't possibly be correct. Lines below should get element i of list, not element 0:

        for (int i = 0; i < privateKeys.size(); i++) {
            KeyPair privateKey = privateKeys.get(0);
            X509Certificate certificate = certificates.get(0);

**Comment by kevinherron** [comment]
Thank you. This has already been fixed in another long running branch but apparently I haven't cherry-picked it over yet 😭

**Comment by kevinherron** [comment]
Oh, nevermind. Didn't realize we were in the digitalpetri project.

This project is no longer maintained. The effort is now here: https://github.com/eclipse/milo

**Comment by lightningrob** [comment]
Thanks for the reply.  I'll look at the milo project and possibly migrate to that.

**Comment by kevinherron** [comment]
It's pretty much a direct continuation of this project. The biggest difference when it comes to migrating is that the package names had to be changed when the project became part of the Eclipse foundation. It happened a while ago, so there may have been some other API changes, but that would be the biggest.
