### ISSUE TITLE
keystore is outdated

### ISSUE THREAD

**Issue by ealprr** [digitalpetri/opc-ua-stack#7]
Trying to run examples, I am getting an exception with ``Bad_CertificateTimeInvalid`` status.
Indeed, it seems that the keys in exemple-keystore are outdated.

Is there something special to know in order to generate a new keystore?

**Comment by kevinherron** [comment]
Ah, the certificates are indeed expired at this point.

I'll update them and include a shell script that invokes keytool for generating new ones in the future. You could do it yourself, in theory, but there's a bunch of extensions and other parts that need to be present for the certificate to pass all the validation tests the spec calls for. 

Using something like [KeyStore Explorer](http://keystore-explorer.sourceforge.net/) you can browse the keystore and view the certificates pretty easily.
