### ISSUE TITLE
Affero or Apache?

### ISSUE THREAD

**Issue by awcullen** [digitalpetri/opc-ua-stack#9]
Can these 5 files from opc-ua-stack be changed from GNU Affero to Apache?
ExecutionQueue.java
ConversionUtil.java
ReferenceType.java
BuiltinReferenceType.java
BuiltinDataType.java
AttributeId.java
Thanks, Andrew

**Comment by kevinherron** [comment]
Oops. Yep. I'll make sure it's part of the 1.0.2 release (this week).
